/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 동행 게시글 목록 조회
     * @description 모집중인 동행 게시글 목록을 조건에 따라 조회합니다.
     */
    get: operations['getPosts'];
    put?: never;
    /**
     * 게시글 작성
     * @description 로그인한 사용자가 게시글을 작성합니다.
     */
    post: operations['createPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/posts/{postId}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 댓글 목록 조회
     * @description 게시글에 작성된 댓글 목록을 작성 시간 오름차순으로 조회합니다.
     */
    get: operations['getComments'];
    put?: never;
    /**
     * 댓글 작성
     * @description 로그인한 사용자가 게시글에 댓글을 작성합니다.
     */
    post: operations['createComment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/images/presigned-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 이미지 업로드용 presigned URL 발급
     * @description 클라이언트가 S3에 직접 PUT할 수 있는 presigned URL을 발급합니다.
     *
     *     - presigned URL의 유효 시간은 발급 후 5분입니다.
     *     - 지원하는 Content-Type: image/jpeg, image/png, image/webp
     *     - 응답의 uploadUrl로 이미지 바이너리를 PUT 요청하면 업로드가 완료되며,
     *       imageUrl은 업로드 완료 후 게시글/프로필 등록 시 사용하는 최종 이미지 URL입니다.
     */
    post: operations['createPresignedUrl'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chat-rooms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 채팅방 목록 조회
     * @description 로그인한 사용자가 참여 중인 채팅방 목록을 조회합니다.
     */
    get: operations['getChatRooms'];
    put?: never;
    /**
     * 채팅방 생성
     * @description 상대방과의 1:1 채팅방이 없으면 생성하고, 이미 있으면 기존 채팅방을 반환합니다.
     */
    post: operations['createChatRoom'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/reissue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * JWT 재발급
     * @description 리프레시 토큰을 이용해 새로운 JWT를 발급합니다.
     */
    post: operations['reissue'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/kakao': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 카카오 로그인
     * @description 카카오 인가 코드를 이용해 로그인하고 JWT를 발급합니다.
     */
    post: operations['kakaoLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/onboarding': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 온보딩 완료
     * @description 관심 국가/도시, 교환학생 정보(선택), 태그, 프로필 정보를 저장하여 온보딩을 완료합니다.
     */
    patch: operations['completeOnboarding'];
    trace?: never;
  };
  '/api/v1/posts/{postId}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 모집 상태 변경
     * @description 게시글 작성자가 모집 상태를 변경합니다.
     */
    patch: operations['updatePostStatus'];
    trace?: never;
  };
  '/api/v1/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 타 유저 프로필 조회
     * @description 특정 사용자의 프로필과 태그를 조회합니다.
     */
    get: operations['getUserProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{userId}/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 타 유저가 작성한 게시글 목록 조회
     * @description 특정 사용자가 작성한 게시글 목록을 조회합니다.
     */
    get: operations['getUserPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 프로필 조회
     * @description 로그인한 사용자의 프로필과 태그를 조회합니다.
     */
    get: operations['getMyProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내가 작성한 게시글 목록 조회
     * @description 로그인한 사용자가 작성한 게시글 목록을 조회합니다.
     */
    get: operations['getMyPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tags/{type}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 태그 목록 조회
     * @description type(ACTIVITY, INTEREST, TRAVEL_STYLE)에 해당하는 태그 목록을 반환합니다.
     */
    get: operations['getTags'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recommendations/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 추천 사용자 조회
     * @description 관심 국가가 같고 취향 태그 유사도가 높은 순으로 추천 사용자를 조회합니다.
     */
    get: operations['getRecommendedUsers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recommendations/users/exchange-country': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 같은 파견 국가 추천 사용자 조회
     * @description 로그인한 사용자와 같은 파견 국가를 가진 사용자 중 온보딩 태그 일치율이 높은 사용자를 조회합니다.
     */
    get: operations['getExchangeCountryRecommendedUsers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recommendations/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 추천 게시글 조회
     * @description 관심 국가가 같고 모집 중이며 취향 태그 유사도가 높은 순으로 추천 게시글을 조회합니다.
     */
    get: operations['getRecommendedPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/posts/{postId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 게시글 상세 조회
     * @description 동행 모집 게시글의 상세 정보를 조회합니다.
     */
    get: operations['getPostDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/countries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 국가 목록 조회
     * @description 전체 국가 목록을 ㄱㄴㄷ순으로 무한 스크롤 조회합니다.
     */
    get: operations['getCountries'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/countries/{countryId}/universities/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 대학교 검색
     * @description 특정 국가(countryId)에 속한 대학교를 이름으로 검색합니다.
     *
     *     - 파견국가 선택 화면에서 국가를 먼저 고른 뒤, 그 국가에 속한 대학교만 목록으로 노출할 때 사용합니다.
     *     - keyword는 대소문자 구분 없이 부분 일치(contains)로 검색되며, 검색 결과는 대학교 이름 오름차순으로 정렬됩니다.
     *     - 다른 국가에 동명의 대학교가 있어도 결과에 섞이지 않고 countryId로 지정한 국가로만 범위가 제한됩니다.
     *     - 커서 없는 Slice 기반 페이지네이션을 사용하며, 다음 페이지 존재 여부는 응답의 hasNext로 확인합니다.
     */
    get: operations['searchUniversities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/countries/{countryId}/cities/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 도시 검색
     * @description 특정 국가에 속한 도시를 검색합니다.
     */
    get: operations['searchCities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/countries/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 국가 검색
     * @description 검색 키워드에 해당하는 국가를 검색합니다.
     */
    get: operations['searchCountries'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chat-rooms/{chatRoomId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 채팅방 상세 조회
     * @description 채팅방 ID로 채팅방 기본 정보와 상대방 정보를 조회합니다.
     */
    get: operations['getChatRoom'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chat-rooms/{chatRoomId}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 채팅 메시지 목록 조회
     * @description 채팅방의 메시지 목록을 커서 기반으로 조회합니다.
     */
    get: operations['getMessages'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreatePostRequest: {
      /**
       * Format: int64
       * @description 국가 ID
       * @example 1
       */
      countryId: number;
      /**
       * Format: int64
       * @description 도시 ID
       * @example 10
       */
      cityId: number;
      /**
       * Format: date
       * @description 동행 시작일
       * @example 2026-09-06
       */
      startDate: string;
      /**
       * Format: date
       * @description 동행 종료일
       * @example 2026-09-19
       */
      endDate: string;
      /**
       * @description 게시글 제목
       * @example 주말에 파리 근교 함께 가실 분!
       */
      title: string;
      /**
       * @description 게시글 본문
       * @example 안녕하세요. 파리 근교 여행 동행을 구합니다.
       */
      content: string;
      /**
       * @description 희망 나이 조건. EARLY_20S(20대 초반), MID_20S(20대 중반), LATE_20S(20대 후반), OVER_30S(30대 이상). 중복 선택 가능
       * @example [
       *       "EARLY_20S",
       *       "MID_20S"
       *     ]
       */
      ageConditions: ('EARLY_20S' | 'MID_20S' | 'LATE_20S' | 'OVER_30S')[];
      /**
       * @description 성별 조건. MALE(남성), FEMALE(여성). 성별 무관은 모두 선택
       * @example [
       *       "MALE",
       *       "FEMALE"
       *     ]
       */
      genderConditions: ('MALE' | 'FEMALE')[];
      /**
       * @description 동행 유형. FULL_TRIP(여행 전체 동행), PARTIAL_TRIP(여행 부분 동행), ACCOMMODATION_SHARE(숙박 공유), TOUR(투어 동행), MEAL(식사 동행), DAILY_LIFE(생활 동행), GROUP_PURCHASE(공동 구매)
       * @example FULL_TRIP
       * @enum {string}
       */
      companionType:
        | 'FULL_TRIP'
        | 'PARTIAL_TRIP'
        | 'ACCOMMODATION_SHARE'
        | 'TOUR'
        | 'MEAL'
        | 'DAILY_LIFE'
        | 'GROUP_PURCHASE';
      /**
       * @description 모집 인원. UNDECIDED(미정), ONE(1인), TWO(2인), THREE(3인), FOUR_OR_MORE(4인 이상)
       * @example TWO
       * @enum {string}
       */
      recruitmentCountType:
        | 'UNDECIDED'
        | 'ONE'
        | 'TWO'
        | 'THREE'
        | 'FOUR_OR_MORE';
      /**
       * @description 연결할 태그 ID 목록
       * @example [
       *       1,
       *       2,
       *       3
       *     ]
       */
      tagIds: number[];
      /**
       * @description 이미 업로드된 게시글 이미지 URL 목록
       * @example [
       *       "https://example.com/post-image.png"
       *     ]
       */
      imageUrls?: string[];
    };
    BaseResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: unknown;
    };
    BaseResponseCreatePostResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['CreatePostResponse'];
    };
    CreatePostResponse: {
      /**
       * Format: int64
       * @description 생성된 게시글 ID
       * @example 1
       */
      postId?: number;
    };
    CreateCommentRequest: {
      /**
       * @description 댓글 내용
       * @example 저도 같이 가고 싶어요!
       */
      content: string;
    };
    BaseResponseCreateCommentResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['CreateCommentResponse'];
    };
    CreateCommentResponse: {
      /**
       * Format: int64
       * @description 생성된 댓글 ID
       * @example 1
       */
      commentId?: number;
    };
    PresignedUrlRequest: {
      /**
       * @description 이미지가 사용될 도메인 (POST: 게시글, PROFILE: 프로필)
       * @example POST
       * @enum {string}
       */
      imageDomain: 'POST' | 'PROFILE';
      /**
       * @description 업로드할 이미지의 Content-Type. image/jpeg, image/png, image/webp만 허용됩니다.
       * @example image/jpeg
       * @enum {string}
       */
      contentType: 'image/jpeg' | 'image/png' | 'image/webp';
      /**
       * Format: int64
       * @description 업로드할 파일 크기(byte). 최대 10MB(10485760)까지 허용됩니다.
       * @example 204800
       */
      fileSize: number;
    };
    BaseResponsePresignedUrlResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['PresignedUrlResponse'];
    };
    PresignedUrlResponse: {
      /**
       * @description 클라이언트가 파일을 PUT할 presigned URL. 발급 후 5분간만 유효합니다.
       * @example https://buddys-assets.s3.ap-northeast-2.amazonaws.com/posts/3f1e...jpg?X-Amz-Algorithm=...
       */
      uploadUrl?: string;
      /**
       * @description 업로드 완료 후 게시글/프로필 등록 시 사용할 최종 이미지 URL
       * @example https://buddys-assets.s3.ap-northeast-2.amazonaws.com/posts/3f1e....jpg
       */
      imageUrl?: string;
    };
    CreateChatRoomRequest: {
      /**
       * Format: int64
       * @description 채팅방을 생성할 상대방 사용자 ID
       * @example 2
       */
      participantUserId: number;
    };
    BaseResponseChatRoomResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ChatRoomResponse'];
    };
    ChatParticipantResponse: {
      /**
       * Format: int64
       * @description 상대방 사용자 ID
       * @example 2
       */
      userId?: number;
      /**
       * @description 상대방 닉네임
       * @example 민지
       */
      nickname?: string;
      /**
       * @description 상대방 프로필 이미지 URL
       * @example https://example.com/profile.png
       */
      profileImageUrl?: string;
    };
    ChatRoomResponse: {
      /**
       * Format: int64
       * @description 채팅방 ID
       * @example 1
       */
      chatRoomId?: number;
      /**
       * Format: date-time
       * @description 채팅방 생성 시각. UTC 기준입니다.
       * @example 2026-07-07T14:30:00Z
       */
      createdAt?: string;
      /** @description 상대방 사용자 정보 */
      participant?: components['schemas']['ChatParticipantResponse'];
    };
    BaseResponseLoginResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['LoginResponse'];
    };
    LoginResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      userId?: number;
      /** @description API 인증에 사용하는 Access Token */
      accessToken?: string;
      /** @description 온보딩(성별/생년월일/태그 3개) 완료 여부 */
      onboardingCompleted?: boolean;
    };
    OnboardingRequest: {
      /**
       * Format: int64
       * @description 관심 국가 ID
       * @example 31
       */
      interestCountryId: number;
      /**
       * Format: int64
       * @description 관심 도시 ID
       * @example 20692
       */
      interestCityId: number;
      /**
       * Format: int64
       * @description 교환학생 국가 ID
       * @example 35
       */
      exchangeCountryId?: number | null;
      /**
       * @description 교환학생 대학교
       * @example Technical University of Munich
       */
      exchangeUniversity?: string | null;
      /**
       * @description 교환학생 시작 연월
       * @example 2027-03
       */
      exchangeStartDate?: string | null;
      /**
       * @description 교환학생 종료 연월
       * @example 2027-08
       */
      exchangeEndDate?: string | null;
      /**
       * @description 활동 태그 ID 목록. 1~3개
       * @example [
       *       1,
       *       2,
       *       3
       *     ]
       */
      activityTagIds: number[];
      /**
       * @description 관심사 태그 ID 목록. 1~3개
       * @example [
       *       13,
       *       26
       *     ]
       */
      interestTagIds: number[];
      /**
       * @description 여행 스타일 태그 ID 목록. 1~5개
       * @example [
       *       27,
       *       30
       *     ]
       */
      travelStyleTagIds: number[];
      /**
       * @description 닉네임. 최대 14자
       * @example 버디즈
       */
      nickname: string;
      /**
       * @description 성별
       * @example FEMALE
       * @enum {string}
       */
      gender: 'MALE' | 'FEMALE';
      /**
       * Format: date
       * @description 생년월일
       * @example 2000-04-02
       */
      birthDate: string;
      /**
       * @description 자기소개. 최대 69자
       * @example 버디즈 화이팅!
       */
      bio?: string | null;
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/profile.png
       */
      profileImageUrl?: string | null;
    };
    BaseResponseOnboardingResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['OnboardingResponse'];
    };
    OnboardingResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      userId?: number;
      /**
       * @description 사용자 닉네임
       * @example 해령
       */
      nickname?: string;
    };
    UpdatePostStatusRequest: {
      /**
       * @description 변경할 모집 상태
       * @example COMPLETED
       * @enum {string}
       */
      status: 'RECRUITING' | 'COMPLETED';
    };
    BaseResponseUpdatePostStatusResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['UpdatePostStatusResponse'];
    };
    UpdatePostStatusResponse: {
      /**
       * Format: int64
       * @description 게시글 ID
       * @example 1
       */
      postId?: number;
      /**
       * @description 변경된 모집 상태
       * @example COMPLETED
       * @enum {string}
       */
      status?: 'RECRUITING' | 'COMPLETED';
    };
    BaseResponseUserPublicProfileResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['UserPublicProfileResponse'];
    };
    TagGroupResponse: {
      /**
       * @description 태그 타입
       * @example ACTIVITY
       * @enum {string}
       */
      tagType?: 'ACTIVITY' | 'INTEREST' | 'TRAVEL_STYLE';
      /**
       * @description 해당 타입의 전체 태그 이름 목록
       * @example [
       *       "액티비티",
       *       "맛집탐방"
       *     ]
       */
      tags?: string[];
    };
    UserPublicProfileResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      userId?: number;
      /**
       * @description 닉네임
       * @example 버디
       */
      nickname?: string;
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/profile.png
       */
      profileImageUrl?: string;
      /**
       * @description 자기소개
       * @example 같이 여행해요!
       */
      bio?: string;
      /**
       * @description 프로필에 표시할 인증 뱃지
       * @example SOCIAL_LOGIN
       * @enum {string}
       */
      verificationBadge?:
        | 'SOCIAL_LOGIN'
        | 'UNIVERSITY_VERIFIED'
        | 'EXCHANGE_VERIFIED';
      /**
       * @description 대표 취향 태그
       * @example [
       *       "문화생활",
       *       "액티비티",
       *       "활발한"
       *     ]
       */
      representativeTags?: string[];
      /** @description 전체 취향 태그 */
      allTags?: components['schemas']['TagGroupResponse'][];
      /**
       * @description 삭제된 사용자 여부
       * @example false
       */
      isDeleted?: boolean;
    };
    BaseResponseUserPostsResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['UserPostsResponse'];
    };
    PostResponse: {
      /**
       * Format: int64
       * @description 게시글 ID
       * @example 1
       */
      postId?: number;
      /**
       * @description 게시글 제목
       * @example 주말에 파리 근교 함께 가실 분!
       */
      title?: string;
      /**
       * @description 게시글 본문
       * @example 안녕하세요. 스쿠버다이빙 가실 분 구합니다.
       */
      content?: string;
      /**
       * @description 게시글 썸네일 이미지 URL
       * @example https://example.com/post-thumbnail.png
       */
      thumbnailImageUrl?: string;
      /**
       * Format: date
       * @description 동행 시작일
       * @example 2026-07-23
       */
      startDate?: string;
      /**
       * Format: date
       * @description 동행 종료일
       * @example 2026-07-28
       */
      endDate?: string;
    };
    UserPostsResponse: {
      /** @description 사용자가 작성한 게시글 목록 */
      posts?: components['schemas']['PostResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지 번호. 0부터 시작합니다.
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지 크기
       * @example 10
       */
      size?: number;
      /**
       * @description 다음 페이지 존재 여부
       * @example true
       */
      hasNext?: boolean;
    };
    BaseResponseUserProfileResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['UserProfileResponse'];
    };
    UserProfileResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      userId?: number;
      /**
       * @description 닉네임
       * @example 버디
       */
      nickname?: string;
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/profile.png
       */
      profileImageUrl?: string;
      /**
       * @description 자기소개
       * @example 같이 여행해요!
       */
      bio?: string;
      /**
       * @description 프로필에 표시할 인증 뱃지
       * @example SOCIAL_LOGIN
       * @enum {string}
       */
      verificationBadge?:
        | 'SOCIAL_LOGIN'
        | 'UNIVERSITY_VERIFIED'
        | 'EXCHANGE_VERIFIED';
      /**
       * @description 대표 취향 태그
       * @example [
       *       "문화생활",
       *       "액티비티",
       *       "활발한"
       *     ]
       */
      representativeTags?: string[];
      /** @description 전체 취향 태그 */
      allTags?: components['schemas']['TagGroupResponse'][];
    };
    BaseResponseListTagResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['TagResponse'][];
    };
    TagResponse: {
      /**
       * Format: int64
       * @description 태그 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 태그 이름
       * @example 여행
       */
      name?: string;
    };
    BaseResponseRecommendedUserListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RecommendedUserListResponse'];
    };
    RecommendedUserListResponse: {
      /** @description 추천 사용자 리스트 */
      users?: components['schemas']['RecommendedUserResponse'][];
    };
    RecommendedUserResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      userId?: number;
      /**
       * @description 사용자 닉네임
       * @example 버디즈
       */
      nickname?: string;
      /** @description 프로필 이미지 주소 */
      profileImageUrl?: string;
      /**
       * Format: int32
       * @description 유사도
       */
      similarityScore?: number;
    };
    BaseResponseExchangeCountryRecommendedUserListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ExchangeCountryRecommendedUserListResponse'];
    };
    ExchangeCountryRecommendedUserListResponse: {
      /** @description 추천 사용자 목록 */
      users?: components['schemas']['ExchangeCountryRecommendedUserResponse'][];
    };
    ExchangeCountryRecommendedUserResponse: {
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 1
       */
      userId?: number;
      /**
       * @description 사용자 닉네임
       * @example 가윤
       */
      nickname?: string;
      /** @description 파견 국가 */
      exchangeCountry?: components['schemas']['ExchangeCountryResponse'];
      /**
       * @description 연령대
       * @example 20대
       */
      ageRange?: string;
      /**
       * Format: int32
       * @description 매칭 퍼센트
       * @example 87
       */
      matchingPercentage?: number;
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/profile.png
       */
      profileImageUrl?: string;
    };
    ExchangeCountryResponse: {
      /**
       * Format: int64
       * @description 국가 ID
       * @example 1
       */
      countryId?: number;
      /**
       * @description 국가 이름
       * @example France
       */
      name?: string;
    };
    BaseResponseRecommendedPostListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['RecommendedPostListResponse'];
    };
    PeriodResponse: {
      /**
       * Format: date
       * @description 시작일
       * @example 2027-03-01
       */
      startDate?: string;
      /**
       * Format: date
       * @description 종료일
       * @example 2027-08-31
       */
      endDate?: string;
    };
    RecommendedPostCountryResponse: {
      /**
       * Format: int64
       * @description 국가 ID
       * @example 1
       */
      countryId?: number;
      /**
       * @description 국가 이름
       * @example France
       */
      name?: string;
    };
    RecommendedPostListResponse: {
      /** @description 추천 게시글 리스트 */
      posts?: components['schemas']['RecommendedPostResponse'][];
    };
    RecommendedPostResponse: {
      /**
       * Format: int64
       * @description 게시글 ID
       * @example 1
       */
      postId?: number;
      /**
       * @description 게시글 제목
       * @example 같이 유럽 여행 가실 분!
       */
      title?: string;
      /** @description 게시글 내용 */
      content?: string;
      /** @description 모집 기간 */
      period?: components['schemas']['PeriodResponse'];
      /** @description 썸네일 이미지 주소 */
      thumbnailUrl?: string | null;
      /** @description 작성자 프로필 이미지 URL */
      authorProfileImageUrl?: string | null;
      /** @description 게시글 국가 */
      country?: components['schemas']['RecommendedPostCountryResponse'];
      /**
       * Format: int64
       * @description 조회수
       * @example 10
       */
      viewCount?: number;
    };
    BaseResponsePostListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['PostListResponse'];
    };
    PostListResponse: {
      /** @description 게시글 목록 */
      content?: components['schemas']['PostSummaryResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지 번호. 0부터 시작합니다.
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지 크기
       * @example 10
       */
      size?: number;
      /**
       * @description 다음 페이지 존재 여부
       * @example true
       */
      hasNext?: boolean;
    };
    PostSummaryCountryResponse: {
      /**
       * Format: int64
       * @description 국가 ID
       * @example 1
       */
      countryId?: number;
      /**
       * @description 국가 이름
       * @example France
       */
      name?: string;
    };
    PostSummaryResponse: {
      /**
       * Format: int64
       * @description 게시글 ID
       * @example 1
       */
      postId?: number;
      /**
       * @description 게시글 제목
       * @example 주말에 파리 근교 함께 가실 분!
       */
      title?: string;
      /**
       * @description 게시글 본문
       * @example 같이 맛집이랑 관광지 다니실 분 구해요.
       */
      content?: string;
      /** @description 국가 */
      country?: components['schemas']['PostSummaryCountryResponse'];
      /**
       * Format: date
       * @description 동행 시작일
       * @example 2026-07-23
       */
      startDate?: string;
      /**
       * Format: date
       * @description 동행 종료일
       * @example 2026-07-28
       */
      endDate?: string;
      /**
       * Format: int32
       * @description 동행 총 일수
       * @example 6
       */
      durationDays?: number;
      /**
       * @description 모집 상태
       * @example RECRUITING
       * @enum {string}
       */
      recruitmentStatus?: 'RECRUITING' | 'COMPLETED';
      /**
       * @description 대표 이미지 URL
       * @example https://example.com/thumbnail.png
       */
      thumbnailImageUrl?: string;
    };
    AuthorResponse: {
      /**
       * Format: int64
       * @description 작성자 ID
       * @example 10
       */
      userId?: number;
      /**
       * @description 작성자 닉네임
       * @example 김가윤
       */
      nickname?: string;
      /**
       * @description 작성자 프로필 이미지 URL
       * @example https://example.com/profile.png
       */
      profileImageUrl?: string;
      /**
       * @description 작성자 국가
       * @example 대한민국
       */
      country?: string;
      /**
       * Format: int32
       * @description 작성자 나이
       * @example 24
       */
      age?: number;
      /**
       * @description 작성자 나이대
       * @example 20대
       */
      ageRange?: string;
      /**
       * @description 작성자 성별
       * @example FEMALE
       * @enum {string}
       */
      gender?: 'MALE' | 'FEMALE';
    };
    BaseResponsePostDetailResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['PostDetailResponse'];
    };
    ConditionsResponse: {
      /** @description 선호 나이 조건 */
      ageConditions?: ('EARLY_20S' | 'MID_20S' | 'LATE_20S' | 'OVER_30S')[];
      /**
       * @description 성별 조건
       * @example [
       *       "MALE",
       *       "FEMALE"
       *     ]
       */
      genderConditions?: ('MALE' | 'FEMALE')[];
      /**
       * @description 동행 유형
       * @example MEAL
       * @enum {string}
       */
      travelType?:
        | 'FULL_TRIP'
        | 'PARTIAL_TRIP'
        | 'ACCOMMODATION_SHARE'
        | 'TOUR'
        | 'MEAL'
        | 'DAILY_LIFE'
        | 'GROUP_PURCHASE';
      /** @description 활동 태그 목록 */
      activityTags?: components['schemas']['PostTagResponse'][];
      /** @description 관심사 태그 목록 */
      interestTags?: components['schemas']['PostTagResponse'][];
      /** @description 여행 스타일 태그 목록 */
      travelStyleTags?: components['schemas']['PostTagResponse'][];
    };
    PostDetailCityResponse: {
      /**
       * Format: int64
       * @description 도시 ID
       * @example 1
       */
      cityId?: number;
      /**
       * @description 도시 이름
       * @example Tokyo
       */
      name?: string;
      /**
       * @description 도시 한글 이름
       * @example 도쿄
       */
      koreanName?: string;
    };
    PostDetailCountryResponse: {
      /**
       * Format: int64
       * @description 국가 ID
       * @example 1
       */
      countryId?: number;
      /**
       * @description 국가 이름
       * @example France
       */
      name?: string;
    };
    PostDetailResponse: {
      /**
       * Format: int64
       * @description 게시글 ID
       * @example 1
       */
      postId?: number;
      /** @description 작성자 정보 */
      author?: components['schemas']['AuthorResponse'];
      /**
       * @description 로그인 사용자의 게시글 여부
       * @example false
       */
      isMine?: boolean;
      /**
       * @description 모집 상태
       * @example RECRUITING
       * @enum {string}
       */
      recruitmentStatus?: 'RECRUITING' | 'COMPLETED';
      /**
       * @description 게시글 제목
       * @example 도쿄 같이 여행할 동행 구해요
       */
      title?: string;
      /** @description 첨부 이미지 URL 목록 */
      imageUrls?: string[];
      /** @description 동행 모집 국가 */
      country?: components['schemas']['PostDetailCountryResponse'];
      /** @description 동행 모집 도시 */
      city?: components['schemas']['PostDetailCityResponse'];
      /**
       * Format: date
       * @description 동행 일정 시작일
       * @example 2026-07-20
       */
      startDate?: string;
      /**
       * Format: date
       * @description 동행 일정 종료일
       * @example 2026-07-22
       */
      endDate?: string;
      /**
       * @description 모집 인원 타입
       * @example TWO
       * @enum {string}
       */
      recruitmentCountType?:
        | 'UNDECIDED'
        | 'ONE'
        | 'TWO'
        | 'THREE'
        | 'FOUR_OR_MORE';
      /**
       * @description 게시글 본문
       * @example 같이 맛집이랑 관광지 다니실 분 구해요.
       */
      content?: string;
      /** @description 동행 조건 */
      conditions?: components['schemas']['ConditionsResponse'];
      /**
       * Format: int64
       * @description 조회수
       * @example 11
       */
      viewCount?: number;
      /**
       * Format: int64
       * @description 댓글 수
       * @example 3
       */
      commentCount?: number;
      /**
       * Format: date-time
       * @description 게시글 생성일시
       * @example 2027-02-20T14:30:00
       */
      createdAt?: string;
    };
    PostTagResponse: {
      /**
       * Format: int64
       * @description 태그 ID
       * @example 1
       */
      tagId?: number;
      /**
       * @description 태그 이름
       * @example 맛집
       */
      name?: string;
    };
    BaseResponseCommentListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['CommentListResponse'];
    };
    CommentListResponse: {
      /** @description 댓글 목록 */
      comments?: components['schemas']['CommentResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지 번호. 0부터 시작합니다.
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지 크기
       * @example 20
       */
      size?: number;
      /**
       * @description 다음 페이지 존재 여부
       * @example true
       */
      hasNext?: boolean;
    };
    CommentResponse: {
      /**
       * Format: int64
       * @description 댓글 ID
       * @example 1
       */
      commentId?: number;
      /**
       * Format: int64
       * @description 댓글 작성자 사용자 ID
       * @example 10
       */
      writerId?: number;
      /**
       * @description 댓글 작성자 이름
       * @example 유저 1
       */
      writerName?: string;
      /**
       * @description 댓글 작성자 프로필 이미지 URL
       * @example https://example.com/profile.png
       */
      writerProfileImageUrl?: string | null;
      /**
       * @description 댓글 내용
       * @example 저도 관심 있어요! DM 보낼게요.
       */
      content?: string;
      /**
       * Format: date-time
       * @description 댓글 작성 시간
       * @example 2026-07-09T21:00:00
       */
      createdAt?: string;
      /**
       * @description 상대 작성 시간
       * @example 1시간 전
       */
      timeAgo?: string;
    };
    BaseResponseCountryListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['CountryListResponse'];
    };
    CountryListResponse: {
      countries?: components['schemas']['CountryResponse'][];
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      hasNext?: boolean;
    };
    CountryResponse: {
      /**
       * Format: int64
       * @description 국가 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 국가 이름
       * @example 대한민국
       */
      name?: string;
      /**
       * @description 국가 코드
       * @example KR
       */
      code?: string;
    };
    BaseResponseUniversityListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['UniversityListResponse'];
    };
    UniversityListResponse: {
      /** @description 검색된 대학교 목록. keyword가 없으면 항상 빈 리스트입니다. */
      universities?: components['schemas']['UniversityResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지 번호 (0부터 시작)
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지 크기
       * @example 20
       */
      size?: number;
      /**
       * @description 다음 페이지 존재 여부
       * @example false
       */
      hasNext?: boolean;
    };
    UniversityResponse: {
      /**
       * Format: int64
       * @description 대학교 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 대학교 이름
       * @example Yonsei University
       */
      name?: string;
      /**
       * @description 대학교 도메인
       * @example yonsei.ac.kr
       */
      domain?: string | null;
    };
    BaseResponseCityListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['CityListResponse'];
    };
    CityListResponse: {
      cities?: components['schemas']['CityResponse'][];
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      hasNext?: boolean;
    };
    CityResponse: {
      /**
       * Format: int64
       * @description 도시 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 도시 이름(영문)
       * @example Seoul
       */
      name?: string;
      /**
       * @description 도시 이름(한글)
       * @example 서울
       */
      koreanName?: string | null;
    };
    BaseResponseChatRoomListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ChatRoomListResponse'];
    };
    ChatRoomListItemResponse: {
      /**
       * Format: int64
       * @description 채팅방 ID
       * @example 1
       */
      chatRoomId?: number;
      /** @description 상대방 사용자 정보 */
      participant?: components['schemas']['ChatParticipantResponse'];
      /**
       * @description 마지막 메시지
       * @example 내일 몇 시에 만날까요?
       */
      lastMessage?: string;
      /**
       * Format: date-time
       * @description 마지막 메시지 시각. UTC 기준입니다.
       * @example 2026-07-05T14:30:00Z
       */
      lastMessageSentAt?: string;
      /**
       * Format: int64
       * @description 읽지 않은 메시지 수
       * @example 3
       */
      unreadMessageCount?: number;
    };
    ChatRoomListResponse: {
      /** @description 채팅방 목록 */
      chatRooms?: components['schemas']['ChatRoomListItemResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지 번호. 0부터 시작합니다.
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지 크기
       * @example 20
       */
      size?: number;
      /**
       * @description 다음 페이지 존재 여부
       * @example true
       */
      hasNext?: boolean;
    };
    BaseResponseChatMessageListResponse: {
      success?: boolean;
      code?: string;
      message?: string;
      data?: components['schemas']['ChatMessageListResponse'];
    };
    ChatMessageListResponse: {
      /** @description 메시지 목록 */
      messages?: components['schemas']['ChatMessageResponse'][];
      /**
       * Format: date-time
       * @description 다음 페이지 커서 메시지 전송 시각. UTC 기준입니다.
       * @example 2026-07-07T14:30:00Z
       */
      nextCursorSentAt?: string;
      /**
       * Format: int64
       * @description 다음 페이지 커서 메시지 ID
       * @example 101
       */
      nextCursorMessageId?: number;
      /**
       * @description 다음 페이지 존재 여부
       * @example true
       */
      hasNext?: boolean;
    };
    ChatMessageResponse: {
      /**
       * Format: int64
       * @description 메시지 ID
       * @example 101
       */
      messageId?: number;
      /** @description 보낸 사용자 정보 */
      sender?: components['schemas']['ChatParticipantResponse'];
      /**
       * @description 메시지 내용
       * @example 안녕하세요!
       */
      content?: string;
      /**
       * Format: date-time
       * @description 메시지 전송 시각. UTC 기준입니다.
       * @example 2026-07-07T14:30:00Z
       */
      sentAt?: string;
      /**
       * @description 내가 보낸 메시지 여부
       * @example false
       */
      mine?: boolean;
      /**
       * @description 메시지를 읽어야 하는 사용자가 읽은 여부
       * @example true
       */
      isRead?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getPosts: {
    parameters: {
      query?: {
        /**
         * @description 제목 또는 본문 검색어
         * @example 파리
         */
        keyword?: string;
        /**
         * @description 국가 ID
         * @example 1
         */
        countryId?: number;
        /**
         * @description 검색 시작일
         * @example 2026-07-23
         */
        startDate?: string;
        /**
         * @description 검색 종료일
         * @example 2026-07-28
         */
        endDate?: string;
        /** @description 나이 조건 목록 */
        ageConditions?: ('EARLY_20S' | 'MID_20S' | 'LATE_20S' | 'OVER_30S')[];
        /** @description 성별 조건 목록 */
        genderConditions?: ('MALE' | 'FEMALE')[];
        /** @description 동행 유형 목록 */
        companionTypes?: (
          | 'FULL_TRIP'
          | 'PARTIAL_TRIP'
          | 'ACCOMMODATION_SHARE'
          | 'TOUR'
          | 'MEAL'
          | 'DAILY_LIFE'
          | 'GROUP_PURCHASE'
        )[];
        /**
         * @description 태그 ID
         * @example 1
         */
        tagId?: number;
        /**
         * @description 페이지 번호. 0 이상입니다.
         * @example 0
         */
        page?: number;
        /**
         * @description 페이지 크기. 1 이상 100 이하입니다.
         * @example 20
         */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePostListResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePostRequest'];
      };
    };
    responses: {
      /** @description 작성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCreatePostResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 국가, 도시, 태그 또는 사용자를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCreatePostResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getComments: {
    parameters: {
      query?: {
        /**
         * @description 페이지 번호. 0 이상입니다.
         * @example 0
         */
        page?: number;
        /**
         * @description 페이지 크기. 1 이상 100 이하입니다.
         * @example 20
         */
        size?: number;
      };
      header?: never;
      path: {
        /**
         * @description 댓글 목록을 조회할 게시글 ID
         * @example 1
         */
        postId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCommentListResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 게시글을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCommentListResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 댓글을 작성할 게시글 ID
         * @example 1
         */
        postId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCommentRequest'];
      };
    };
    responses: {
      /** @description 작성 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCreateCommentResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 게시글 또는 사용자를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCreateCommentResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  createPresignedUrl: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PresignedUrlRequest'];
      };
    };
    responses: {
      /** @description 발급 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePresignedUrlResponse'];
        };
      };
      /** @description 지원하지 않는 이미지 형식 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "IMG-E001",
           *       "message": "지원하지 않는 이미지 형식입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getChatRooms: {
    parameters: {
      query?: {
        /**
         * @description 페이지 번호. 0 이상입니다.
         * @example 0
         */
        page?: number;
        /**
         * @description 페이지 크기. 1 이상 100 이하입니다.
         * @example 20
         */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 채팅방 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseChatRoomListResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "USER-E001",
           *       "message": "사용자를 찾을 수 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  createChatRoom: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateChatRoomRequest'];
      };
    };
    responses: {
      /** @description 채팅방 조회 또는 생성 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseChatRoomResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "USER-E001",
           *       "message": "사용자를 찾을 수 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  reissue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        /** @description 리프레시 토큰 */
        refreshToken?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description JWT 재발급 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseLoginResponse'];
        };
      };
      /** @description 리프레시 토큰이 유효하지 않음 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseLoginResponse'];
        };
      };
    };
  };
  kakaoLogin: {
    parameters: {
      query: {
        /**
         * @description 카카오 OAuth 인가 코드
         * @example kaO7zQSSJXT...
         */
        code: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 로그인 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseLoginResponse'];
        };
      };
      /** @description 잘못된 인가 코드 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseLoginResponse'];
        };
      };
    };
  };
  completeOnboarding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "interestCountryId": 31,
         *       "interestCityId": 20692,
         *       "exchangeCountryId": 71,
         *       "exchangeUniversity": "Harvard University",
         *       "exchangeStartDate": "2027-03",
         *       "exchangeEndDate": "2027-08",
         *       "activityTagIds": [
         *         1,
         *         2,
         *         3
         *       ],
         *       "interestTagIds": [
         *         13,
         *         26
         *       ],
         *       "travelStyleTagIds": [
         *         27,
         *         30
         *       ],
         *       "nickname": "버디즈",
         *       "gender": "FEMALE",
         *       "birthDate": "2004-02-22",
         *       "bio": "같이 여행 다녀요!",
         *       "profileImageUrl": "https://example.com/profile.png"
         *     }
         */
        'application/json': components['schemas']['OnboardingRequest'];
      };
    };
    responses: {
      /** @description 온보딩 완료 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseOnboardingResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자, 태그, 국가 또는 도시 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 닉네임 중복 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "AUTH-E003",
           *       "message": "이미 사용 중인 닉네임입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  updatePostStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 모집 상태를 변경할 게시글 ID
         * @example 1
         */
        postId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePostStatusRequest'];
      };
    };
    responses: {
      /** @description 변경 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseUpdatePostStatusResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 게시글 작성자가 아님 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseUpdatePostStatusResponse'];
        };
      };
      /** @description 게시글을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseUpdatePostStatusResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getUserProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 조회할 사용자 ID
         * @example 1
         */
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 타 유저 프로필 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseUserPublicProfileResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "USER-E001",
           *       "message": "사용자를 찾을 수 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getUserPosts: {
    parameters: {
      query?: {
        /**
         * @description 페이지 번호. 0 이상입니다.
         * @example 0
         */
        page?: number;
        /**
         * @description 페이지 크기. 1 이상 100 이하입니다.
         * @example 10
         */
        size?: number;
      };
      header?: never;
      path: {
        /**
         * @description 조회할 사용자 ID
         * @example 1
         */
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 타 유저가 작성한 게시글 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseUserPostsResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "USER-E001",
           *       "message": "사용자를 찾을 수 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getMyProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 내 프로필 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseUserProfileResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "USER-E001",
           *       "message": "사용자를 찾을 수 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getMyPosts: {
    parameters: {
      query?: {
        /**
         * @description 페이지 번호. 0 이상입니다.
         * @example 0
         */
        page?: number;
        /**
         * @description 페이지 크기. 1 이상 100 이하입니다.
         * @example 10
         */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 내가 작성한 게시글 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseUserPostsResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "USER-E001",
           *       "message": "사용자를 찾을 수 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getTags: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 태그 타입
         * @example ACTIVITY
         */
        type: 'ACTIVITY' | 'INTEREST' | 'TRAVEL_STYLE';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseListTagResponse'];
        };
      };
      /** @description 유효하지 않은 태그 타입 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseListTagResponse'];
        };
      };
    };
  };
  getRecommendedUsers: {
    parameters: {
      query?: {
        /**
         * @description 조회할 개수. 1 이상 10이하입니다.
         * @example 1
         */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 추천 사용자 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseRecommendedUserListResponse'];
        };
      };
      /** @description 관심 국가 미설정 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "REC-E001",
           *       "message": "관심 국가를 설정해주세요.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "USER-E001",
           *       "message": "사용자를 찾을 수 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getExchangeCountryRecommendedUsers: {
    parameters: {
      query?: {
        /**
         * @description 조회할 개수. 1 이상 10 이하입니다.
         * @example 5
         */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseExchangeCountryRecommendedUserListResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseExchangeCountryRecommendedUserListResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getRecommendedPosts: {
    parameters: {
      query?: {
        /**
         * @description 조회할 개수. 1 이상 10이하입니다.
         * @example 4
         */
        size?: number;
        /**
         * @description 이미지 있는 게시물만 조회할지 여부. true면 이미지 있는 게시물만 조회, false면 이미지 없는 게시물도 포함
         * @example false
         */
        requireImage?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 추천 게시글 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseRecommendedPostListResponse'];
        };
      };
      /** @description 관심 국가 미설정 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "REC-E001",
           *       "message": "관심 국가를 설정해주세요.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 사용자 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "USER-E001",
           *       "message": "사용자를 찾을 수 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getPostDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 조회할 게시글 ID
         * @example 1
         */
        postId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePostDetailResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 게시글을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePostDetailResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getCountries: {
    parameters: {
      query?: {
        /**
         * @description 페이지 번호. 0 이상입니다.
         * @example 0
         */
        page?: number;
        /**
         * @description 페이지 크기. 1 이상 100이하입니다.
         * @example 20
         */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCountryListResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  searchUniversities: {
    parameters: {
      query?: {
        /**
         * @description 검색 키워드. 대소문자 구분 없이 대학교 이름에 부분 일치합니다. 생략하거나 빈 문자열/공백만 전달하면 빈 리스트가 반환됩니다.
         * @example Yonsei
         */
        keyword?: string;
        /**
         * @description 페이지 번호. 0 이상입니다.
         * @example 0
         */
        page?: number;
        /**
         * @description 페이지 크기. 1 이상 100 이하입니다.
         * @example 20
         */
        size?: number;
      };
      header?: never;
      path: {
        /**
         * @description 국가 ID. 존재하지 않는 ID를 전달하면 404가 반환됩니다.
         * @example 31
         */
        countryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 검색 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseUniversityListResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 국가를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "LOC-E001",
           *       "message": "국가를 찾을 수 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  searchCities: {
    parameters: {
      query: {
        /**
         * @description 검색 키워드
         * @example 서울
         */
        keyword: string;
        /**
         * @description 페이지 번호. 0 이상입니다.
         * @example 0
         */
        page?: number;
        /**
         * @description 페이지 크기. 1 이상 100 이하입니다.
         * @example 20
         */
        size?: number;
      };
      header?: never;
      path: {
        /**
         * @description 국가 ID
         * @example 32
         */
        countryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 검색 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCityListResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 국가 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCityListResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  searchCountries: {
    parameters: {
      query: {
        /**
         * @description 검색 키워드
         * @example 대한민국
         */
        keyword: string;
        /**
         * @description 페이지 번호. 0 이상입니다.
         * @example 0
         */
        page?: number;
        /**
         * @description 페이지 크기. 1 이상 100이하입니다.
         * @example 20
         */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 검색 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseCountryListResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getChatRoom: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 조회할 채팅방 ID
         * @example 1
         */
        chatRoomId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 채팅방 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseChatRoomResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 채팅방 접근 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E003",
           *       "message": "접근 권한이 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 채팅방 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
  getMessages: {
    parameters: {
      query?: {
        /**
         * @description 커서 메시지 전송 시각. UTC 기준입니다.
         * @example 2026-07-07T14:30:00Z
         */
        cursorSentAt?: string;
        /**
         * @description 커서 메시지 ID
         * @example 101
         */
        cursorMessageId?: number;
        /**
         * @description 조회 개수. 1 이상 100 이하입니다.
         * @example 30
         */
        size?: number;
      };
      header?: never;
      path: {
        /**
         * @description 조회할 채팅방 ID
         * @example 1
         */
        chatRoomId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 채팅 메시지 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseChatMessageListResponse'];
        };
      };
      /** @description 잘못된 요청 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E001",
           *       "message": "잘못된 요청입니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 인증 필요 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E002",
           *       "message": "인증이 필요합니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 채팅방 접근 권한 없음 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E003",
           *       "message": "접근 권한이 없습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 채팅방 또는 사용자 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BaseResponse'];
        };
      };
      /** @description 서버 내부 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "GLB-E005",
           *       "message": "서버 내부 오류가 발생했습니다.",
           *       "data": null
           *     }
           */
          'application/json': components['schemas']['BaseResponse'];
        };
      };
    };
  };
}
