name: Auto Label

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited]

permissions:
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Add label from PR title and author
        uses: actions/github-script@v7
        with:
          script: |
            const typeLabels = {
              docs: '📄 DOCS',
              feat: '✨ FEAT',
              init: '🌱 INIT',
              fix: '💦 FIX',
              refactor: '🎀 REFACTOR',
              chore: '📍 CHORE',
              deploy: '🪄 DEPLOY',
            }

            const authorLabels = {
              'jin-evergreen': '🐵 진석',
              winchoose: '🐸 승택',
              jinaaaaaaaaaaaaa: '🐹 진아',
              ahyohyo: '🐶 효정',
              seojin15: '🐟 서진',
            }

            const pullRequest = context.payload.pull_request
            const title = pullRequest.title
            const author = pullRequest.user.login
            const match = title.match(
              /^\[(init|feat|fix|docs|refactor|chore|deploy)\]/i,
            )

            if (!match) {
              core.info(`No PR type found in title: ${title}`)
            }

            const type = match?.[1].toLowerCase()
            const typeLabel = type ? typeLabels[type] : null
            const authorLabel = authorLabels[author]

            const currentLabels = pullRequest.labels.map(({ name }) => name)
            const typeLableNames = Object.values(typeLabels)

            const labelsToRemove = currentLabels.filter(
              (label) => typeLableNames.includes(label) && label !== typeLabel,
            )

            for (const label of labelsToRemove) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pullRequest.number,
                name: label,
              })
            }

            const labelsToAdd = [typeLabel, authorLabel].filter((label) => label)

            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pullRequest.number,
                labels: labelsToAdd,
              })
            }
